# This Code is used to Play Pre-recoreded Audio as per input given by User
# This Code is generated By Mr.Rajendra Rajput
# Dated: 16.04.2017

import pyaudio
import wave
import sys


class AudioFile:
    chunk = 1024

    def __init__(self, file):
        """ Init audio stream """ 
        self.wf = wave.open(file, 'rb')         # Object of Wave
        self.p = pyaudio.PyAudio()              # Object of pyaudio
        self.stream = self.p.open(
            format = self.p.get_format_from_width(self.wf.getsampwidth()),
            channels = self.wf.getnchannels(),
            rate = self.wf.getframerate(),
            output = True
        )

    def play(self):
        """ Play entire file """
        data = self.wf.readframes(self.chunk)
        while data != '':
            self.stream.write(data)
            data = self.wf.readframes(self.chunk)

    def close(self):
        """ Graceful shutdown """ 
        self.stream.close()
        self.p.terminate()



##hide = AudioFile("hide.wav")
##hide.play()
##hide.close()

    # Usage example for pyaudio
def hide():
        hide = AudioFile("hide.wav")
        hide.play()
        hide.close()
        return 0
        
def lays():
        lays = AudioFile("lays.wav")
        lays.play()
        lays.close()
        return 0
        
def magi():
        magi = AudioFile("magi.wav")
        magi.play()
        magi.close()
        return 0
        
def parleg():
        parle = AudioFile("parleg.wav")
        parle.play()
        parle.close()
        return 0
        
def wheel():
        wheel = AudioFile("wheel.wav")
        wheel.play()
        wheel.close()
        return 0
    
print(" This is the Program for for Audio Input by Mr. Rajput")
print(" The Program is Made by Mr. Rajput")
print("\n\t 1. hide")
print("\n\t 2. lays")
print("\n\t 3. magi")
print("\n\t 4. parleg")
print("\n\t 5. wheels")

name = str(input(" Please enter the Audio NUMBER or Name  you want to hear:"))
##print name 
##D = {'hide': "hide.play()" , 'lays': "lays.play()", 'maggi': magi.play(),'parleg':parle.play(),'wheels':wheel.play() }
s1 = "hide"
s2 = "lays"
s3 = "magi"
s4 = "parleg"
s5 = "wheels"

if name.isdigit()== True :
        if name == '1':
           hide()
        elif name == '2':
            lays()
        elif name == '3':
            magi()
        elif  name == '4':
            parleg()
        elif name == '5':
            wheel()
        else:
            print " ---- "
else:
        name1 = input(" Please enter the Audio Name  given above:")
        if  hide == name1:
           hide()
        elif lays == name1:
            lays()
        elif magi == name1:
            magi()
        elif  parleg == name1:
            parleg()
        elif wheel == name1:
            wheel()
        else :
            print "Thanks for your input "
